apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy

metadata:
  name: {{ include "prom-crds-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prom-crds-proxy.labels" . | nindent 4 }}
  {{- with .Values.annotation }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  clusterSelector:
    {{- toYaml .Values.target.selector | nindent 4 }}

  repoURL: https://prometheus-community.github.io/helm-charts
  chartName: prometheus-operator-crds
  version: {{ .Values.upstream.version | default (printf "v%s" .Chart.AppVersion) }}
  releaseName: {{ .Values.target.release }}
  namespace: {{ .Values.target.namespace }}
  reconcileStrategy: InstallOnce

  options:
    waitForJobs: true
    wait: true
    timeout: 5m
    install:
      createNamespace: false
      includeCRDs: true
