{{- if and .Values.metrics.enabled }}
apiVersion: v1
kind: Service

metadata:
  name: {{ template "hcloud-csi-user.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hcloud-csi-user.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
{{- end }}
{{- if  .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
{{- end }}

spec:
  type: {{ .Values.service.type }}

  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP

  selector:
    {{- include "hcloud-csi-user.selectorLabels" . | nindent 4 }}
{{- end }}
