kind: StorageClass
apiVersion: storage.k8s.io/v1

metadata:
  name: hcloud
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"

provisioner: csi.hetzner.cloud
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: "Delete"
