apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "hcloud-ccm-mgmt.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hcloud-ccm-mgmt.labels" . | nindent 4 }}
  {{- with .Values.annotation }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  {{- if .Values.updateStrategy }}

  strategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}

  selector:
    matchLabels:
      {{- include "hcloud-ccm-mgmt.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "hcloud-ccm-mgmt.labels" . | nindent 8 }}
      {{- if  .Values.annotations }}
      annotations:
        {{- toYaml .Values.annotations | nindent 8 }}
      {{- end }}

    spec:
      serviceAccountName: {{ include "hcloud-ccm-mgmt.serviceAccountName" . }}
      {{- if .Values.image.pullSecrets }}

      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- with .Values.securityContext }}

      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.extraInitContainers }}

      initContainers:
        {{- toYaml .Values.extraInitContainers | nindent 8 }}
      {{- end }}

      containers:
        - name: hcloud-ccm
          image: {{ .Values.image.controller.repository }}:{{ .Values.image.controller.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.controller.pullPolicy }}

          args:
            - --cluster-cidr={{ .Values.config.clusterCidr }}
            {{- if .Values.config.kubeconfig }}
            - --authentication-kubeconfig=/run/secrets/hcloud-ccm/value
            - --authorization-kubeconfig=/run/secrets/hcloud-ccm/value
            - --kubeconfig=/run/secrets/hcloud-ccm/value
            {{- end }}
            - --allocate-node-cidrs=true
            - --allow-untagged-cloud
            - --cloud-provider=hcloud
            - --route-reconciliation-period=30s
            - --webhook-secure-port=0
            - --leader-elect=false
          {{- with .Values.podSecurityContext.controller }}

          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          env:
            - name: HCLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hetzner
                  key: hcloud
            {{- if .Values.config.network }}
            - name: HCLOUD_NETWORK
              value: "{{ .Values.config.network }}"
            {{- end }}
            {{- if .Values.extraEnvVariables }}
            {{- toYaml .Values.extraEnvVariables | nindent 12 }}
            {{- end }}
          {{- if .Values.metrics.enabled }}

          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.internalPort }}
              protocol: TCP
          {{- end }}
          {{- if .Values.resources }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if or .Values.config.kubeconfig .Values.extraVolumeMounts }}

          volumeMounts:
            {{- if .Values.config.kubeconfig }}
            - mountPath: /run/secrets/hcloud-ccm
              name: kubeconfig
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
          {{- end }}
        {{- if .Values.extraSidecarContainers }}
        {{- toYaml .Values.extraSidecarContainers | nindent 8 }}
        {{- end }}
      {{- if .Values.nodeSelector }}

      nodeSelector:
        {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}

      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}

      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.config.kubeconfig .Values.extraVolumes }}

      volumes:
        {{- if .Values.config.kubeconfig }}
        - name: kubeconfig
          secret:
            secretName: {{ .Values.config.kubeconfig }}
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
      {{- end }}
