apiVersion: v1
kind: Service

metadata:
  name: {{ template "ansible-semaphore.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ansible-semaphore.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
{{- end }}
{{- if  .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
{{- end }}

spec:
  type: {{ .Values.service.type }}

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP

  selector:
    {{- include "ansible-semaphore.selectorLabels" . | nindent 4 }}
