apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy

metadata:
  name: {{ include "hcloud-ccm-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hcloud-ccm-proxy.labels" . | nindent 4 }}
  {{- with .Values.annotation }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  clusterSelector:
    {{- toYaml .Values.target.selector | nindent 4 }}

  repoURL: https://charts.hetzner.cloud
  chartName: hcloud-cloud-controller-manager
  version: {{ .Values.upstream.version }}
  releaseName: {{ .Values.target.release }}
  namespace: {{ .Values.target.namespace }}
  reconcileStrategy: Continuous

  options:
    waitForJobs: true
    wait: true
    timeout: 5m
    install:
      createNamespace: false
      includeCRDs: true

  valuesTemplate: |
    nameOverride: {{ .Values.target.release }}

    env:
      HCLOUD_TOKEN:
        valueFrom:
          secretKeyRef:
            name: hetzner
            key: hcloud

      HCLOUD_INSTANCES_ADDRESS_FAMILY:
        value: "dualstack"
      HCLOUD_LOAD_BALANCERS_ENABLED:
        value: "true"
      HCLOUD_LOAD_BALANCERS_NETWORK_ZONE:
        value: "eu-central"
      HCLOUD_LOAD_BALANCERS_DISABLE_IPV6:
        value: "false"
      HCLOUD_LOAD_BALANCERS_DISABLE_PRIVATE_INGRESS:
        value: "true"
      HCLOUD_LOAD_BALANCERS_USE_PRIVATE_IP:
        value: "true"

    networking:
      enabled: true
      clusterCIDR: {{ printf "{{ index .Cluster.spec.clusterNetwork.pods.cidrBlocks 0 }}" }}
      network:
        valueFrom:
          secretKeyRef:
            name: hetzner
            key: network

    monitoring:
      enabled: true
      podMonitor:
        enabled: true

    additionalTolerations:
      - key: node.cluster.x-k8s.io/uninitialized
        effect: NoSchedule
        operator: Exists
      - key: node.kubernetes.io/not-ready
        effect: NoSchedule
        operator: Exists
